# Generated by Django 5.2.15 on 2026-07-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('eyebrow', models.CharField(blank=True, max_length=128, verbose_name='Eyebrow')),
                ('lead', models.TextField(blank=True, verbose_name='Lead')),
                ('body', models.TextField(blank=True, verbose_name='Тіло (HTML)')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Додаткові дані')),
            ],
            options={
                'verbose_name': 'Сторінка контенту',
                'verbose_name_plural': 'Сторінки контенту',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': 'Питання FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст відгуку')),
                ('author', models.CharField(max_length=128, verbose_name='Автор')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='066 320 28 62', max_length=32, verbose_name='Телефон')),
                ('phone_intl', models.CharField(default='+380 66 320 28 62', max_length=32, verbose_name='Телефон (міжнародний)')),
                ('phone_href', models.CharField(default='+380663202862', max_length=32, verbose_name='Телефон (href)')),
                ('email', models.EmailField(default='oksanadaragan9@gmail.com', max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='м. Київ, просп. Палладіна Академіка, 23а', max_length=255, verbose_name='Адреса')),
                ('hours', models.CharField(default='щодня з 8:00 до 19:00', max_length=128, verbose_name='Години роботи')),
                ('name', models.CharField(default='ZOO МАГАЗИН WILLI', max_length=128, verbose_name='Назва магазину')),
                ('map_lat', models.DecimalField(decimal_places=6, default=50.464137, max_digits=9, verbose_name='Широта')),
                ('map_lng', models.DecimalField(decimal_places=6, default=30.35462, max_digits=9, verbose_name='Довгота')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
