# Generated by Django 4.2.21 on 2026-07-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='До 80 символів', max_length=80, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, help_text='До 200 символів', max_length=200, verbose_name='Підзаголовок')),
                ('cta_text', models.CharField(help_text='До 48 символів, напр. «До каталогу»', max_length=48, verbose_name='Текст кнопки')),
                ('cta_url', models.CharField(help_text='Відносний шлях: /catalog/, /promotions/, /delivery/', max_length=128, verbose_name='Посилання кнопки')),
                ('image', models.ImageField(help_text='Рекомендовано: 1920×1080 px, JPG або WebP, до 3 МБ', upload_to='hero/', verbose_name='Зображення')),
                ('object_position', models.CharField(blank=True, default='center center', help_text='CSS object-position: top, center center, 30% 50% тощо', max_length=32, verbose_name='Позиція фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Банер головної',
                'verbose_name_plural': 'Банери головної',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='contentpage',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Рекомендовано: 1440×480 px, JPG або WebP, до 1.5 МБ', upload_to='pages/', verbose_name='Зображення заголовку сторінки'),
        ),
    ]
