# Generated by Django 4.2.21 on 2026-07-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_heroslide_contentpage_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='google_review_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='ID відгуку Google'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, help_text='Від 1 до 5 зірок', verbose_name='Оцінка'),
        ),
        migrations.AddField(
            model_name='review',
            name='show_on_homepage',
            field=models.BooleanField(default=True, help_text='Відображати в блоці «Що кажуть клієнти» на головній сторінці.', verbose_name='Показувати на головній'),
        ),
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(choices=[('manual', 'Вручну'), ('google', 'Google Maps')], default='manual', max_length=16, verbose_name='Джерело'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Посилання на сторінку магазину в Google Maps (для кнопки «Відкрити на карті»).', max_length=512, verbose_name='Посилання на Google Maps'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='Для автоматичного імпорту відгуків (заповнюється командою sync_google_reviews).', max_length=128, verbose_name='Google Place ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.TextField(blank=True, help_text='Вставте значення src з коду вбудовування Google Maps. Рекомендований розмір: 600×450 px.', verbose_name='Код карти Google (iframe src)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hours',
            field=models.CharField(default='щодня з 9:00 до 20:00', max_length=128, verbose_name='Години роботи'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_lat',
            field=models.DecimalField(decimal_places=6, default=50.466266, max_digits=9, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_lng',
            field=models.DecimalField(decimal_places=6, default=30.354818, max_digits=9, verbose_name='Довгота'),
        ),
    ]
