# Generated by Django 4.2.21 on 2026-07-08 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review_google_review_id_review_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=4, verbose_name='Крок')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('intro', models.TextField(blank=True, verbose_name='Вступ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Секція доставки',
                'verbose_name_plural': 'Секції доставки',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(choices=[('categories', 'Категорії'), ('sale_products', 'Акційні товари'), ('reviews', 'Відгуки'), ('cta', 'CTA-блок')], unique=True, verbose_name='Ключ')),
                ('label', models.CharField(max_length=64, verbose_name='Назва в адмінці')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показувати')),
                ('eyebrow', models.CharField(blank=True, max_length=128, verbose_name='Eyebrow')),
                ('heading', models.CharField(blank=True, max_length=128, verbose_name='Заголовок')),
                ('subheading', models.CharField(blank=True, max_length=255, verbose_name='Підзаголовок')),
                ('image', models.ImageField(blank=True, help_text='Фонове зображення. Рекомендовано: 1440×800 px, JPG/WebP, до 2 МБ', upload_to='blocks/', verbose_name='Зображення')),
                ('perk_1', models.CharField(blank=True, max_length=128, verbose_name='Перевага 1')),
                ('perk_2', models.CharField(blank=True, max_length=128, verbose_name='Перевага 2')),
                ('perk_3', models.CharField(blank=True, max_length=128, verbose_name='Перевага 3')),
                ('cta_text', models.CharField(blank=True, max_length=64, verbose_name='Текст кнопки')),
                ('cta_url', models.CharField(blank=True, max_length=128, verbose_name='Посилання кнопки')),
            ],
            options={
                'verbose_name': 'Блок головної',
                'verbose_name_plural': 'Блоки головної',
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='contentpage',
            name='empty_text',
            field=models.TextField(blank=True, help_text='Текст, коли акційних товарів немає', verbose_name='Текст порожнього стану'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='note',
            field=models.TextField(blank=True, help_text='Підпис внизу сторінки (FAQ тощо)', verbose_name='Підпис внизу сторінки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Посилання на сторінку магазину в Google Maps.', max_length=512, verbose_name='Посилання на Google Maps'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='Google Place ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.TextField(blank=True, help_text='Google Maps → Поділитися → Вбудувати карту → скопіюйте посилання src.', verbose_name='Код карти Google'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='066 320 28 62', help_text='Наприклад: 066 320 28 62', max_length=32, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='Підпис')),
                ('text', models.TextField(verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.deliverysection', verbose_name='Секція')),
            ],
            options={
                'verbose_name': 'Пункт доставки',
                'verbose_name_plural': 'Пункти доставки',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
