# Generated by Django 4.2.21 on 2026-07-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deliverysection_homeblock_contentpage_empty_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeblock',
            name='custom_review_1_author',
            field=models.CharField(blank=True, max_length=128, verbose_name='Відгук 1 — автор'),
        ),
        migrations.AddField(
            model_name='homeblock',
            name='custom_review_1_text',
            field=models.TextField(blank=True, verbose_name='Відгук 1 — текст'),
        ),
        migrations.AddField(
            model_name='homeblock',
            name='custom_review_2_author',
            field=models.CharField(blank=True, max_length=128, verbose_name='Відгук 2 — автор'),
        ),
        migrations.AddField(
            model_name='homeblock',
            name='custom_review_2_text',
            field=models.TextField(blank=True, verbose_name='Відгук 2 — текст'),
        ),
        migrations.AddField(
            model_name='homeblock',
            name='custom_review_3_author',
            field=models.CharField(blank=True, max_length=128, verbose_name='Відгук 3 — автор'),
        ),
        migrations.AddField(
            model_name='homeblock',
            name='custom_review_3_text',
            field=models.TextField(blank=True, verbose_name='Відгук 3 — текст'),
        ),
        migrations.AddField(
            model_name='homeblock',
            name='reviews_source',
            field=models.CharField(blank=True, choices=[('google', 'Автоматично з Google Maps'), ('admin', 'З розділу «Відгуки»'), ('custom', 'Свої відгуки (вписати нижче)'), ('samples', 'Приклади за замовчуванням')], default='admin', help_text='Лише для блоку «Відгуки».', max_length=16, verbose_name='Звідки брати відгуки'),
        ),
        migrations.AddField(
            model_name='homeblock',
            name='text_mode',
            field=models.CharField(choices=[('default', 'Стандартні тексти'), ('custom', 'Свої тексти')], default='default', help_text='«Стандартні» — тексти як на сайті за замовчуванням. «Свої» — поля нижче.', max_length=16, verbose_name='Тексти заголовка'),
        ),
        migrations.AlterField(
            model_name='homeblock',
            name='eyebrow',
            field=models.CharField(blank=True, help_text='Невеликий рядок над основним заголовком.', max_length=128, verbose_name='Підпис над заголовком'),
        ),
        migrations.AlterField(
            model_name='homeblock',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендовано: 1440×800 px, JPG/WebP, до 2 МБ', upload_to='blocks/', verbose_name='Фонове зображення'),
        ),
        migrations.AlterField(
            model_name='homeblock',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Вимкніть, щоб повністю приховати цей блок на сайті.', verbose_name='Показувати на головній'),
        ),
    ]
