# Generated by Django 4.2.21 on 2026-08-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_homeblock_text_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Коли')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Логін')),
                ('password_length', models.PositiveSmallIntegerField(default=0, verbose_name='Довжина пароля')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('device_summary', models.CharField(blank=True, max_length=255, verbose_name='Пристрій')),
                ('accept_language', models.CharField(blank=True, max_length=128, verbose_name='Мова браузера')),
                ('referer', models.CharField(blank=True, max_length=512, verbose_name='Referer')),
                ('path', models.CharField(default='/admin/', max_length=255, verbose_name='Шлях')),
            ],
            options={
                'verbose_name': 'Спроба входу в адмінку',
                'verbose_name_plural': 'Спроби входу в адмінку',
                'ordering': ['-created_at'],
            },
        ),
    ]
