# Generated by Django 4.2.21 on 2026-08-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_admin_login_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='fop_full_name',
            field=models.CharField(default='Дараган Оксана Юріївна', max_length=128, verbose_name='Повне імʼя ФОП'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fop_rnokpp',
            field=models.CharField(default='3058502902', max_length=16, verbose_name='РНОКПП'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fop_trade_name',
            field=models.CharField(default='ФОП Дараган', help_text='Наприклад: ФОП Дараган', max_length=128, verbose_name='Найменування ФОП'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='fop_unzr',
            field=models.CharField(default='19830927-08140', max_length=32, verbose_name='УНЗР'),
        ),
    ]
