# Generated by Django 5.2.15 on 2026-07-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Кінець акції'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Початок акції'),
        ),
    ]
