# Generated by Django 4.2.21 on 2026-08-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('nova_poshta', 'Нова Пошта — відділення'), ('nova_poshta_address', 'Нова Пошта — адресна доставка'), ('ukrposhta', 'Укрпошта (архів)')], max_length=32, verbose_name='Доставка'),
        ),
    ]
